export const USER_ROLE = "UserRole";
export const ADMIN_ROLE = "AdminRole";
export const UNAUTHORIZED = "Unauthorized";
export const UNAUTHORIZED_MSG = "User is not authorized.";
export const UNAUTHENTICATED = "Unauthenticated";
export const UNAUTHENTICATED_MSG = "User is not authenticated.";
export const GENERATE_BLOG_POST_COST = 10;
export const GENERATE_BLOG_TIME = 44000; // in milliseconds
export const GENERATE_PARAMS_MANUAL_BLOG_TIME = 44000; // in milliseconds
export const GENERATE_PARAMS_NOBLOG_TIME = 1000; // in milliseconds
export const GENERATE_PARAMS_AI_NOBLOG_TIME = 8000; // in milliseconds
